name: lisaem
base: core18 # the base snap is the execution environment for this snap
version: '1.2.7'
summary: The first fully functional Lisa Emulator
description: |
  The first fully functional Lisa Emulator

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

parts:
  wx:
    source: https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.2/wxWidgets-3.1.2.tar.bz2
    plugin: autotools
    configflags: [ "--with-gtk", "--enable-unicode", "--disable-debug", "--disable-shared", "--without-expat",  "--disable-richtext",  "--disable-dynlib",  "--with-libpng=builtin", "--with-libjpeg=builtin", "--with-libtiff=builtin", "--with-libxpm=builtin", "--prefix=/usr/local/wx${VER}-${TYPE}", "--with-libxpm=builtin", "--prefix=/usr/local/wx${VER}-${TYPE}" ]
    build-environment: 
      - CFLAGS: -fPIC
      - CXXFLAGS: -fPIC
    build-packages:
      - build-essential
      - pkg-config
      - libgtk-3-dev
      - libgtk2.0-dev
      - netpbm
      - upx
      - imagemagick
      - liblzma-dev
      - libexpat1-dev
      - libsdl1.2-dev
      - zlib1g-dev
      - libsm-dev
      - libgl1-mesa-dev
      - libxt-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libwebkit2gtk-4.0-dev
      - libnotify-dev
  lisaem:
    after: [wx]
    plugin: nil
    source: https://github.com/rayarachelian/lisaem.git
    override-build: |
      ./build.sh
